# Generated by Django 2.2 on 2020-03-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200309_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
